### ISSUE TITLE
[TODO] The data type for 'unit'

### ISSUE THREAD

**Issue by namse** [NamseEnt/namseent#16]
# Entry Point
common

# What result I am expecting
- The data type
  - can parsed with JSON.parse, keeping method
  - can type-guard on calculation

# Why do you need it
For now, we put suffix like 'ms' or 'px' to tell 'The unit of this value is milliseconds'.
Suffix is good, but the value type is number. Sometime we make a mistake.
I hope some data type can make a type guard and clear it.

**Comment by metalglove** [comment]
If you want to type guard numbers as a unit of time type, I propose you define what the most common unit of time is (e.g. milliseconds or seconds) and use that as the default unit everywhere.
If you document what the standards are throughout your library for special units like time and size, you will be less likely to make mistakes.

Time:
```ts
// define Time type or class
//   add converters to selected time unit (seconds -> milliseconds, minutes -> milliseconds, etc)
//   The backing type can just be the number type (e.g. type Time = number)
const frequency: Time = Time.fromMilliseconds(10);
```

Size:
 ```ts
// define Size type or class
//   add converters to selected Size unit (pixels, centimeters?, etc.)
//   The backing type can just be the number type (e.g. type Size = number)
const width: Size = Size.fromPixels(10);
```

**Comment by namse** [comment]
By the lovely rust type system, I did it already.
https://github.com/NamseEnt/namseent/blob/15cc098ece4ac2fb8f909c1b12f051cad85d7108/luda-editor/luda-editor-client/src/app/types/time.rs
I think this kind of type system is very normal in rust so I won't put any comment here.
