### ISSUE TITLE
[TODO] Sequence List View

### ISSUE THREAD

**Issue by namse** [NamseEnt/namseent#27]
Yes, we have timeline. It's not about timeline.
I think timeline is the editor which can edit only single sequence.
We need some window or view which can select a sequence from sequence list.

# What result I am expecting
- New user experience progress for editor
  - Create new sequence
    - click 'add' button
    - type 'title'
    - good.
  - Editing sequence
    1. Showing sequence lists
    2. click one sequence
    3. open timeline editor
    4. edit, save, go back
    5. goto 1;
- Sequence List View
  - Title(required) and Thumbnail(optional)
  - Thumbnail is the first image of sequence? I have no idea.
- The way to fix title of sequence.

**Comment by namse** [comment]
FYI, This commit implement the way to save and load sequence data. https://github.com/NamseEnt/namseent/commit/2ab54cbf072107f7fa064ecf7fd5b7c0448eb9a6

**Comment by bigfoodK** [comment]
### TODO
- [x] List sequence titles
- [x] Open sequence
- [ ] Top bar(back to list button) in editor
- [ ] Create sequence
- [ ] Rename sequence
- [ ] Delete sequence

**Comment by bigfoodK** [comment]
Closed with #88, #95
