### ISSUE TITLE
Bundle fail to serve for `filename:filename`

### ISSUE THREAD

**Issue by namse** [NamseEnt/namseent#318]
bundle endpoint fail to provide with 404 when I put bundle like below

```
// .namuibundle
setting.json:setting.json
```

request url: http://localhost:8080/bundle/setting.json

**Comment by bigfoodK** [comment]
Just file name only will works.
```
// .namuibundle
setting.json
```

**Comment by bigfoodK** [comment]
I think we should let the user know usage of `.namuibundle`.

readme.md on namui? or some good way...

**Comment by bigfoodK** [comment]
1. Add readme to namui
2. Add init command like 'cargo init' to namui-cli
3. Generate .namuibundle on 'namui init'
  a. Generated .namuibundle has link to readme and simple commented examples

Then user can easly access readme.


Please let me know if any good ideas

**Comment by namse** [comment]
> readme.md on namui? or some good way...

Anywhere is good. I think we need docs or wiki for our system. 

I think making documentation is better for 2 or 3.
