### ISSUE TITLE
Easy way to preview screen in main cut editor

### ISSUE THREAD

**Issue by namse** [NamseEnt/namseent#449]
It's difficult what kind of face the character makes using current image list on right side.
![image](https://user-images.githubusercontent.com/3580430/202847031-0cd58046-8372-43f6-8f34-7321d2572ec2.png)

I think we need screen preview cell at there.

**Comment by namse** [comment]
What users need to check is,
1. The character who there are on screen
2. The emotion of character at that cut
3. The preview of cut to check how it would be in game

So, Here is my idea,
1. Shows face-crop images with small full body image in image list.
  - face-crop image for character & emotion detect.
    - Crop face using anime-face-detector
  - full body image for pose detect.
2. Add new column for preview. it shows mini-size preview.

**Comment by bigfoodK** [comment]
I think it's outdated
Can we close it? @namse

**Comment by namse** [comment]
Yes
