### ISSUE TITLE
Support shell completion for namui-cli

### ISSUE THREAD

**Issue by namse** [NamseEnt/namseent#468]
https://docs.rs/clap_complete/latest/clap_complete/

**Comment by bigfoodK** [comment]
For bash, we need to add complete script to `~/.bashrc` or `/etc/bash_completion.d/<script_name>`.
I think `~/.bashrc` is more appropriate. because namui-cli install script is for individual not system-wide.

**Comment by bigfoodK** [comment]
Complete script can be generated on both runtime or compile-time.
If we do this on runtime, generating subcommand will be exposed to user.
ex) `$namui generate=bash`

This is not good for user because user don't need this command.
So I think generating script in compile-time is better way.
