### ISSUE TITLE
PR Bug Issue - #47 Fail to run application after `namui -w`

### ISSUE THREAD

**Issue by namse** [NamseEnt/namseent#48]
Linked pull requests: #47 

# Pull request QA Error Reports

# What i did 
1. `git clone`, `cd` and `git pull`
2. `sh namui-cli/scripts/install.sh`
3. `cd luda-editor/luda-editor-client` And `namui -w`
4. browser automatically opened, cli started building.

# What i expected
1. Running application after build

# What happened
1. No application run after build, with error in screenshot.
2. In this situation, if i change code, it doesn't reload automatically.

@bigfoodK 

![image](https://user-images.githubusercontent.com/3580430/147412121-60737268-68cc-4736-91e4-193675b324a8.png)

+

When i reload web page, it still fail to get bundle.
![image](https://user-images.githubusercontent.com/3580430/147412219-ff81fd5c-b907-42ba-9d00-ef30d9fe3347.png)

Even if I restart cli, it's same.

**Comment by namse** [comment]
@bigfoodK Here is the network information in chrome
![image](https://user-images.githubusercontent.com/3580430/147444505-16852e27-509b-4328-90cf-fc88390941aa.png)

**Comment by namse** [comment]
No content in bundle.js

![image](https://user-images.githubusercontent.com/3580430/147444873-254a7f93-125a-474c-b832-d81bec73d3ab.png)

**Comment by namse** [comment]
I got these errors after run `namui -w` (I disabled console clear to check what happened)
![image](https://user-images.githubusercontent.com/3580430/147446780-41af0f26-7c7f-45e7-813b-6463194611c8.png)

**Comment by namse** [comment]
IoError occured here
https://github.com/NamseEnt/namseent/blob/c088d0190b4955722c82f5ff9f53d8d42fc77a2c/namui-cli/src/build/build_server/start_build.rs#L149

**Comment by namse** [comment]
I think this is because host computer didn't install wasm-bindgen.

**Comment by namse** [comment]
@bigfoodK In this issue, they said you should use `wasm-pack` instead of `wasm-bindgen-cli`. would you check it?
https://github.com/rustwasm/wasm-bindgen/issues/2167

**Comment by bigfoodK** [comment]
We just need to apply `wasm-bindgen` to the wasm file. Therefore, it would be better to use `wasm-bindgen-cli` than `wasm-pack`.

Can you check if it's running after install `wasm-bindgen-cli` with `cargo install wasm-bindgen-cli`.

If it runs. I will add it to `install.sh`.

**Comment by namse** [comment]
Actually I failed to install wasm-bindgen-cli in wsl ubuntu.

**Comment by bigfoodK** [comment]
Aaaaah, I got it!
From now on runs `cargo check` instead `cargo build`. And then runs `wasm-pack` instead `wasm-bindgen.`

with 7f077ea

**Comment by namse** [comment]
I checked the commit 7f077ea and it ran very well. good job bigfoodK and i close this comment.
