### ISSUE TITLE
`namui-cli` show wrong indented error in first buliding

### ISSUE THREAD

**Issue by namse** [NamseEnt/namseent#59]
# What I did
- run namui-cli with the code which has error.

# What I expected
- It shows error well

# What happened
- error message has wrong indentation

![image](https://user-images.githubusercontent.com/3580430/148545622-c01c6a40-e3c0-4609-95f6-c6e21ea4d278.png)

**Comment by bigfoodK** [comment]
Can you check if this problem occurs even after this commit(22223b0) in this pr(#71)?
I used the bash of wsl ubuntu 20.04. And there was no problem like this.

**Comment by namse** [comment]
I think this is my vscode terminal's problem. I couldn't find any problem when I pipe console output to text file or using windows terminal. I will open this problem if this trouble occurs there too.
