### ISSUE TITLE
Can not select some variants

### ISSUE THREAD

**Issue by bigfoodK** [NamseEnt/namseent#593]
![Animation](https://github.com/NamseEnt/namseent/assets/38313680/39116182-6ed1-4615-bf08-8f3d3b91ca55)

I don't know which variant causes this issue.

**Comment by namse** [comment]
@bigfoodK give me the psd that you tested

**Comment by namse** [comment]
This? https://drive.google.com/file/d/1s1LSped2b1ss176liNAIEPyV0ZzNhh-u/view?usp=drive_link

**Comment by namse** [comment]
Working well with above psd file.
https://github.com/NamseEnt/namseent/assets/3580430/e04bfe35-acc5-4a92-9a4f-83cf23975fe7

**Comment by bigfoodK** [comment]
I think I found a hint.
Maybe the area of CG covers the variant button?


![Animation](https://github.com/NamseEnt/namseent/assets/38313680/dc206e25-30c5-4d40-91cb-14083503196f)

**Comment by bigfoodK** [comment]
![image](https://github.com/NamseEnt/namseent/assets/38313680/6ec9ccaf-fb77-4ed9-a05b-49ab85391a66)

**Comment by namse** [comment]
Ok Got it

**Comment by namse** [comment]
WTF
![image](https://github.com/NamseEnt/namseent/assets/3580430/3b244b11-b62a-4c58-af3b-db8926d5c953)
