### ISSUE TITLE
Suggestion: Show indicator during upload cg psd files

### ISSUE THREAD

**Issue by namse** [NamseEnt/namseent#601]
Cg psd uploading takes a several seconds so I hope our editor shows indicator like loading spinner.

**Comment by bigfoodK** [comment]
I agree that

**Comment by bigfoodK** [comment]
option 1. loading splash
![image](https://github.com/NamseEnt/namseent/assets/38313680/7e396e51-d572-4831-90cf-4a1954e69cd9)

option 2. notification card
![image](https://github.com/NamseEnt/namseent/assets/38313680/ae60033b-cbd5-4c3b-a29e-511da8b06947)

The big difference between option 1 and 2 is blocking user action.
option 1 blocks user action while uploading.
I don't think there's a need to block user input during the upload.
So I prefer option 2.

What do you think? @namse

**Comment by namse** [comment]
I'm ok with both idea. 

Second one would be needed more caution than First one.

For example, user can put new file during upload. Than it should shows the list of requests and each indicators. Google drive is good case for this.

**Comment by namse** [comment]
Please do this later merging master.
