### ISSUE TITLE
No `match if` for simple checking please~

### ISSUE THREAD

**Issue by namse** [NamseEnt/namseent#694]
https://github.com/NamseEnt/namseent/blob/8cb4c8a37ec98a5a8bf9f80836dc1a4898afdefa/luda-editor/client/src/pages/sequence_edit_page/components/cut_list_view/mod.rs#L160-L171

I think simple if statement with mapping is better for this.

**Comment by bigfoodK** [comment]
Depth and branching can be reduced.
I think this is a good expression of Rust
Is it really hard to read?

**Comment by namse** [comment]
Readability is first. it's very difficult to read and understand.
and That's not true, below code is the same with above match. it has even less depth.

```rust
if !after_cut_id.and(|x| x == dragging.cut_id) {
  ...
}
```

**Comment by namse** [comment]
Take a look this reddit post too https://www.reddit.com/r/rust/comments/13cdhy3/why_using_if_when_we_have_match/

**Comment by bigfoodK** [comment]
Got it. I will fix it

**Comment by namse** [comment]
Old abandoned issue, close.
