### ISSUE TITLE
[Bug]: CORS Error on master list server

### ISSUE THREAD

**Issue by namse** [NamseEnt/namseent#697]
### Expected Behavior

Successfully upload psd cg file

### Actual Behavior

CORS Error during uploading psd cg file

![image](https://github.com/NamseEnt/namseent/assets/3580430/86404108-4e95-431c-9ec0-85ff96b34164)

https://s3.ap-northeast-2.amazonaws.com/luda-editor/master/www/index.html

**Comment by bigfoodK** [comment]
It seems to be problem that occurs because `complete_psd` is too heavy a task.
In lambda log
