### ISSUE TITLE
Namui-cli doesn't send bundle.

### ISSUE THREAD

**Issue by bigfoodK** [NamseEnt/namseent#70]
Today, I face to simillar error that namui doesn't rebuild on changes and doesn't send bundle neither.

https://user-images.githubusercontent.com/3580430/148041885-1aedf9c4-0d32-4de5-a501-9027729862a7.mp4

_Originally posted by @namse in https://github.com/NamseEnt/namseent/issues/53#issuecomment-1004669803_

It looks another problem from #53

**Comment by namse** [comment]
It isn't reproduced for now. Let's reopen when it happen again.
