### ISSUE TITLE
[Bug]: Panic when trying to stroke path with zero width

### ISSUE THREAD

**Issue by bigfoodK** [NamseEnt/namseent#732]
### Expected Behavior

Just not draw stroke if width is zero. not panic.

### Actual Behavior

Panic occurs
```text
Namui system initialized
thread 'main' panicked at /home/bigfood/programming/namseent/namui/skia/skia/src/native/path.rs:113:21:
stroke failed
```

https://github.com/NamseEnt/namseent/blob/d936cee7b131a8ede4deb44f7793ddd196f83259/namui/skia/skia/src/native/path.rs#L106-L114

### Steps to Reproduce

```rust
        ctx.component(simple_rect(
            wh,
            Color::TRANSPARENT,
            0.px(),
            THEME.background.main,
        ));
```

**Comment by namse** [comment]
closed by https://github.com/NamseEnt/namseent/pull/736
