### ISSUE TITLE
[Bug]: Stuck on bundle::read()

### ISSUE THREAD

**Issue by bigfoodK** [NamseEnt/namseent#733]
### Expected Behavior

Read bundle files.

### Actual Behavior

Stuck at bundle::read()

### Steps to Reproduce

Run note register
https://github.com/NamseEnt/namseent/blob/f62ad29900088d21a049d709f2e06e9da733130d/hololive-beat/note-register/src/app/note.rs#L48-L49

**Comment by namse** [comment]
It's not a bug. use namui::spawn instead of tokio::spawn_local.
