### ISSUE TITLE
[Bug]: Opus audio makes strange noise

### ISSUE THREAD

**Issue by bigfoodK** [NamseEnt/namseent#758]
### Expected Behavior

on `namui/sample/media`,
opus should also be able to play like `namui/sample/media/resources/audio.mp3`.

### Actual Behavior

When I play opus, sounds like this. 
[2024-01-02_21-41-29.webm](https://github.com/NamseEnt/namseent/assets/38313680/0433cecf-7d6b-403e-a0a8-56da213442b1)

sound is recorded with obs and coverted from mp4 to webm with `ffmpeg -i recored.mp4 recored.webm` to upload recorded file to github issue.

### Steps to Reproduce

1. Tested on a3aa7ac5711ce8868b959a887ce91a9ae9ffd2f9
2. Use `hololive-beat/note-register/public/you_re_mine.opus` instead `namui/sample/media/resources/audio.mp3` for `namui/sample/media` sample.
   - `cp hololive-beat/note-register/public/you_re_mine.opus namui/sample/media/resources`
   - then change file path to `"bundle:resources/you_re_mine.opus"`
   - [let path = namui::system::file::bundle::to_real_path("bundle:resources/audio.mp3")](https://github.com/NamseEnt/namseent/blob/a3aa7ac5711ce8868b959a887ce91a9ae9ffd2f9/namui/sample/media/src/lib.rs#L19-L20)
   - run media sample and play audio

### Other Info

Tested audio device is
- 48K
- 2ch
- 16bit

**Comment by namse** [comment]
Show your WaveFormat which will print in terminal when you start app
for example
```
[namui-media] Device supports format WaveFormat { nAvgBytesPerSec: 352800, cbSize: 22, nBlockAlign: 8, wBitsPerSample: 32, nSamplesPerSec: 44100, wFormatTag: 65534, wValidBitsPerSample: 32, SubFormat: 00000003-0000-0010-8000-00AA00389B71, nChannel: 2, dwChannelMask: 3 }
```
