### ISSUE TITLE
[Bug]: get_my_teams always return empty vector

### ISSUE THREAD

**Issue by bigfoodK** [NamseEnt/namseent#951]
### Expected Behavior

Return own teams

### Actual Behavior

Empty vector returns

### Steps to Reproduce

https://github.com/NamseEnt/namseent/tree/luda-editor/list-team

1. run server
2. run client
3. login
4. create team
5. reload, then created team should be shown

**Comment by namse** [comment]
![image](https://github.com/user-attachments/assets/275a589e-c7f3-4c42-9d18-5a0ab5aa044f)
